version: '3'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - ./graphite/storage:/opt/graphite/storage
      - ./graphite/conf:/opt/graphite/conf
      #- ./graphite/data/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf